#!/usr/bin/env python3
"""
Webhook Health E2E Tests

Validates that the kagenti-webhook is correctly deployed and configured:
- Deployment is ready with desired replicas
- Pods are in Running phase
- MutatingWebhookConfiguration is registered
- CA bundle is injected by cert-manager (cert rotation works)
- TLS Secret exists (webhook server can serve)

Usage:
    pytest tests/e2e/test_webhook_health.py -v
"""

import pytest
from kubernetes.client.rest import ApiException


# MutatingWebhookConfiguration name generated by kustomize (make deploy)
_KUSTOMIZE_WEBHOOK_CONFIG = "kagenti-webhook-authbridge-mutating-webhook-configuration"
# MutatingWebhookConfiguration name generated by Helm chart
_HELM_WEBHOOK_CONFIG = "kagenti-webhook-authbridge-mutating-webhook-configuration"

# TLS Secret name (cert-manager Certificate -> Secret)
_TLS_SECRET_NAME = "webhook-server-cert"


class TestWebhookDeployment:
    """Verify the kagenti-webhook manager pod is running."""

    def test_webhook_namespace_exists(self, k8s_client, webhook_namespace):
        """Verify the kagenti-webhook namespace exists."""
        try:
            ns = k8s_client.read_namespace(name=webhook_namespace)
            assert ns is not None
        except ApiException as e:
            pytest.fail(
                f"Webhook namespace '{webhook_namespace}' not found: {e}\n"
                "Is the webhook deployed? Run: make deploy IMG=..."
            )

    def test_webhook_deployment_exists(self, k8s_apps_client, webhook_namespace):
        """Verify the kagenti-webhook controller-manager Deployment exists."""
        deployments = k8s_apps_client.list_namespaced_deployment(namespace=webhook_namespace)
        names = [d.metadata.name for d in deployments.items]

        controller_deploys = [n for n in names if "controller-manager" in n or "kagenti-webhook" in n]
        assert len(controller_deploys) >= 1, (
            f"No kagenti-webhook deployment found in '{webhook_namespace}'.\n"
            f"Deployments present: {names}\n"
            "Is the webhook deployed? Run: make deploy IMG=..."
        )

    def test_webhook_deployment_ready(self, k8s_apps_client, webhook_namespace):
        """Verify the kagenti-webhook deployment has all replicas ready."""
        deployments = k8s_apps_client.list_namespaced_deployment(namespace=webhook_namespace)
        controller_deploys = [
            d for d in deployments.items
            if "controller-manager" in d.metadata.name or "kagenti-webhook" in d.metadata.name
        ]

        assert len(controller_deploys) >= 1, (
            f"No kagenti-webhook deployment found in '{webhook_namespace}'"
        )

        deploy = controller_deploys[0]
        desired = deploy.spec.replicas or 1
        ready = deploy.status.ready_replicas or 0

        assert ready >= desired, (
            f"Webhook deployment '{deploy.metadata.name}' not ready: "
            f"{ready}/{desired} replicas\n"
            "Check: kubectl get pods -n " + webhook_namespace
        )

    def test_webhook_pods_running(self, k8s_client, webhook_namespace):
        """Verify at least one kagenti-webhook pod is in Running phase."""
        pods = k8s_client.list_namespaced_pod(
            namespace=webhook_namespace,
            label_selector="control-plane=controller-manager",
        )

        if not pods.items:
            # Fallback: list all pods and find controller-manager pod
            all_pods = k8s_client.list_namespaced_pod(namespace=webhook_namespace)
            pods_items = [
                p for p in all_pods.items
                if "controller-manager" in p.metadata.name
            ]
        else:
            pods_items = pods.items

        assert len(pods_items) >= 1, (
            f"No controller-manager pods found in '{webhook_namespace}'"
        )

        for pod in pods_items:
            assert pod.status.phase == "Running", (
                f"Webhook pod '{pod.metadata.name}' is not Running: {pod.status.phase}"
            )


class TestWebhookConfiguration:
    """Verify the MutatingWebhookConfiguration is registered and healthy."""

    def _find_authbridge_webhook_config(self, k8s_admission_client):
        """Find the AuthBridge MutatingWebhookConfiguration (kustomize or Helm name)."""
        configs = k8s_admission_client.list_mutating_webhook_configuration()
        names = [c.metadata.name for c in configs.items]

        authbridge_configs = [
            c for c in configs.items
            if "authbridge" in c.metadata.name.lower() or "kagenti-webhook" in c.metadata.name.lower()
        ]
        if not authbridge_configs:
            pytest.fail(
                f"No AuthBridge MutatingWebhookConfiguration found.\n"
                f"Existing configurations: {names}\n"
                "Is the webhook deployed?"
            )
        return authbridge_configs[0]

    def test_authbridge_webhook_registered(self, k8s_admission_client):
        """Verify the AuthBridge MutatingWebhookConfiguration is registered."""
        config = self._find_authbridge_webhook_config(k8s_admission_client)
        assert config is not None

        webhook_names = [w.name for w in config.webhooks]
        assert any("inject" in n or "authbridge" in n.lower() for n in webhook_names), (
            f"Expected inject.kagenti.io webhook, found: {webhook_names}"
        )

    def test_authbridge_webhook_has_ca_bundle(self, k8s_admission_client):
        """
        Verify the webhook CA bundle is populated.

        cert-manager injects the CA bundle via the cert-manager.io/inject-ca-from
        annotation. An empty CA bundle means cert-manager hasn't run yet or
        the Certificate resource is missing.
        """
        config = self._find_authbridge_webhook_config(k8s_admission_client)

        for webhook in config.webhooks:
            if "inject" in webhook.name or "authbridge" in webhook.name.lower():
                ca_bundle = webhook.client_config.ca_bundle
                assert ca_bundle and len(ca_bundle) > 10, (
                    f"Webhook '{webhook.name}' has empty or missing CA bundle.\n"
                    "Check: cert-manager is running and Certificate resource is ready.\n"
                    "Run: kubectl get certificate -n kagenti-webhook-system"
                )
                return

        pytest.fail("No inject.kagenti.io webhook entry found in AuthBridge config")

    def test_authbridge_webhook_targets_pods(self, k8s_admission_client):
        """Verify the webhook is configured to intercept Pod CREATE operations."""
        config = self._find_authbridge_webhook_config(k8s_admission_client)

        for webhook in config.webhooks:
            if "inject" in webhook.name or "authbridge" in webhook.name.lower():
                rules = webhook.rules or []
                assert len(rules) >= 1, f"No rules in webhook '{webhook.name}'"

                rule = rules[0]
                assert "CREATE" in rule.operations, (
                    f"Webhook does not intercept CREATE: {rule.operations}"
                )
                assert "" in rule.api_groups or "v1" in rule.api_versions, (
                    f"Webhook does not target core API: groups={rule.api_groups}"
                )
                assert "pods" in rule.resources, (
                    f"Webhook does not target pods: {rule.resources}"
                )
                return

        pytest.fail("inject.kagenti.io webhook entry not found in config")

    def test_webhook_failure_policy_is_fail(self, k8s_admission_client):
        """
        Verify the webhook failurePolicy is Fail.

        With Fail policy, pod creation fails if the webhook is unreachable,
        which is the secure default for AuthBridge (no silent bypass).
        """
        config = self._find_authbridge_webhook_config(k8s_admission_client)

        for webhook in config.webhooks:
            if "inject" in webhook.name or "authbridge" in webhook.name.lower():
                assert webhook.failure_policy == "Fail", (
                    f"Expected failurePolicy=Fail, got: {webhook.failure_policy}"
                )
                return

        pytest.fail("inject.kagenti.io webhook entry not found in config")


class TestCertManagerIntegration:
    """Verify cert-manager has provisioned the webhook TLS certificate."""

    def test_webhook_tls_secret_exists(self, k8s_client, webhook_namespace):
        """
        Verify the webhook TLS Secret was created by cert-manager.

        The webhook server requires this secret for TLS. If missing, the
        webhook cannot serve requests and all pod creations will fail.
        """
        try:
            secret = k8s_client.read_namespaced_secret(
                name=_TLS_SECRET_NAME,
                namespace=webhook_namespace,
            )
            assert secret is not None, f"TLS secret '{_TLS_SECRET_NAME}' is None"

            # Verify it contains the expected TLS data
            assert secret.data is not None, "TLS secret has no data"
            assert "tls.crt" in secret.data, (
                f"TLS secret missing tls.crt. Keys: {list(secret.data.keys())}"
            )
            assert "tls.key" in secret.data, (
                f"TLS secret missing tls.key. Keys: {list(secret.data.keys())}"
            )
        except ApiException as e:
            pytest.fail(
                f"TLS secret '{_TLS_SECRET_NAME}' not found in '{webhook_namespace}': {e}\n"
                "Check: cert-manager is installed and Certificate resource is ready.\n"
                "Run: kubectl get certificate,secret -n kagenti-webhook-system"
            )


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-v"]))
